### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by Smssyed8** [epm-dev-priporov/idea-notes#7] opened 2023-04-13 08:43 UTC
Hi, there is no search as of now,

if file search is done form intellij, yes works, however, if text search is done, it doesnt.

**Comment by epm-dev-priporov** [comment] 2023-04-13 08:49
Hi @Smssyed8 , thank you for the report. Will strive to fix it in the following update

**Comment by epm-dev-priporov** [comment] 2023-04-18 08:14
fixed in v1.2.7

**Closed by epm-dev-priporov** 2023-04-18 08:14 UTC
Labels: enhancement, good first issue

**Comment by Smssyed8** [comment] 2023-04-19 06:55
Thank you for a quick fix. For your time and consideration.

I couldnt get backt to test it as I was away for sometime. 

Much appreciated

**Comment by epm-dev-priporov** [comment] 2023-04-19 07:10
@Smssyed8 I am not able to reproduce, everything if fine for me. Did you choose the NotesTree scope?
![image](https://user-images.githubusercontent.com/30048339/232995105-72c86d03-e0b8-49b1-a158-a3801c4f8f73.png)

![image](https://user-images.githubusercontent.com/30048339/232994627-8604a72d-cc5b-49df-a755-43bcdf5af6bd.png)

**Comment by Smssyed8** [comment] 2023-04-19 07:18
> @Smssyed8 I am not able to reproduce, everything if fine for me. Did you choose the NotesTree scope? ![image](https://user-images.githubusercontent.com/30048339/232995105-72c86d03-e0b8-49b1-a158-a3801c4f8f73.png)
> 
> ![image](https://user-images.githubusercontent.com/30048339/232994627-8604a72d-cc5b-49df-a755-43bcdf5af6bd.png)

yes, scope and directory search are working fine

**Comment by epm-dev-priporov** [comment] 2023-04-19 07:40
> Is it possible to change default location C:\Users\xxxxxxx.ideanotes to custom location for created notes, so that it can be kept backed up

No it's not, but to create backup you can use Export feature and save zip file.

**Comment by Smssyed8** [comment] 2023-04-19 08:15
great thank you, I was facing another issue, we dont have expand all, collapse all, 
Also, I search a file in hierarchy, on search the file is shown and opens in intellij tab, however doesnt show and point to the file in Notes, explorer. As there are child hierarchy files which I want to open and interested in.
